### ISSUE TITLE
Оценка

### ISSUE THREAD

**Issue by DOFONSON** [koldun256/filmopoisk#2]
Привет, а ты отправляешь запрос на изменение рейтинга на сервер?  Вроде как запроса нет ни в дев тулзах ни на сервере

![image](https://github.com/koldun256/filmopoisk/assets/67873840/41589932-ba0d-4fb5-a139-305b2cdc1154)
![image](https://github.com/koldun256/filmopoisk/assets/67873840/140dd36d-0e59-4071-b1a8-a5048ccc7787)

Если пользователь не авторизован, то рейтинг фильма ему не виден
![image](https://github.com/koldun256/filmopoisk/assets/67873840/a6ad916e-c776-4e21-8e20-6b62b36ad3fa)

Также, если говорить про некст, то при перезагрузке страницы на странице фильма происходит страшное
![image](https://github.com/koldun256/filmopoisk/assets/67873840/9cbae5da-9f89-42c2-a623-a3560d3159a3)
Ну и также не уходит запрос на изменение, вернее как, он уходит, но не туда (404 ошибка), также не подгружаются картиночки звездочек и профиля.
![image](https://github.com/koldun256/filmopoisk/assets/67873840/9ecf4da9-d651-4037-a569-d900550a108f)

И последнее, при перезагрузке страницы, пользователь слетает и ему снова нужно авторизироваться.

Могу в сумме поставить 90 баллов, снял:
Общие требования - 1 балл, за то, что пользователю не виден общий рейтинг фильма без авторизации, сам рейтинг тоже не виден
Страница фильма - 4 балла, за то, что рейтинг не виден, а также нет запроса на его изменение при клике на кнопки.

Next
Реализована миграция с использованием SSR - 5 баллов за то, что было перечислено выше.

Если согласен с оценкой или хочешь обсудить детали, то напиши об этом, оценку пока не ставлю, жду твоего ответа

**Comment by koldun256** [comment]
Да, согласен с 90, странно что запрос на рейтинг не уходит. Спасибо что так подробно расписал

**Comment by DOFONSON** [comment]
Не за что)
